# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Inputview = PlotWidget(self.groupBox_3)
        self.Inputview.setMinimumSize(QtCore.QSize(0, 120))
        self.Inputview.setObjectName("Inputview")
        self.verticalLayout_6.addWidget(self.Inputview)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Outview_1 = PlotWidget(self.groupBox)
        self.Outview_1.setObjectName("Outview_1")
        self.horizontalLayout.addWidget(self.Outview_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Start_1 = QtWidgets.QPushButton(self.groupBox)
        self.Start_1.setObjectName("Start_1")
        self.verticalLayout_2.addWidget(self.Start_1)
        self.Stop_1 = QtWidgets.QPushButton(self.groupBox)
        self.Stop_1.setObjectName("Stop_1")
        self.verticalLayout_2.addWidget(self.Stop_1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Outview_2 = PlotWidget(self.groupBox_2)
        self.Outview_2.setObjectName("Outview_2")
        self.horizontalLayout_2.addWidget(self.Outview_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.Start_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Start_2.setObjectName("Start_2")
        self.verticalLayout_3.addWidget(self.Start_2)
        self.Stop_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Stop_2.setObjectName("Stop_2")
        self.verticalLayout_3.addWidget(self.Stop_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.save_outputs = QtWidgets.QPushButton(self.groupBox_2)
        self.save_outputs.setMaximumSize(QtCore.QSize(300, 16777215))
        self.save_outputs.setObjectName("save_outputs")
        self.verticalLayout_5.addWidget(self.save_outputs)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 26))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionImport)
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input Fourier"))
        self.groupBox.setTitle(_translate("MainWindow", "Channel 1 Fourier"))
        self.label.setText(_translate("MainWindow", "Output 1 player"))
        self.Start_1.setText(_translate("MainWindow", "Start"))
        self.Stop_1.setText(_translate("MainWindow", "Stop"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Channel 2 Fourier"))
        self.label_2.setText(_translate("MainWindow", "Output 2 player"))
        self.Start_2.setText(_translate("MainWindow", "Start"))
        self.Stop_2.setText(_translate("MainWindow", "Stop"))
        self.save_outputs.setText(_translate("MainWindow", "Save Outputs"))
        self.menuImport.setTitle(_translate("MainWindow", "Menu"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
